apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-nfs-etc
spec:
  storageClassName: "nfs-etc"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: PIHOLE_ETC_NFS_PATH           # < NFS share path on the server
    server: NFS_SERVER_IP               # < IP number of your NFS server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-nfs-dnsmasq
spec:
  storageClassName: "nfs-dnsmasq"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: PIHOLE_DNSMASQ_NFS_PATH      # < NFS share path on the server
    server: NFS_SERVER_IP              # < IP address of your NFS server
    readOnly: false
