apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-etc
provisioner: example.com/external-nfs
parameters:
  server: NFS_SERVER_IP               # < IP number of your NFS server
  path: PIHOLE_ETC_NFS_PATH           # < NFS share path on the server
  readOnly: "false"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-dnsmasq
provisioner: example.com/external-nfs
parameters:
  server: NFS_SERVER_IP              # < IP address of your NFS server
  path: PIHOLE_DNSMASQ_NFS_PATH      # < NFS share path on the server
  readOnly: "false"
